### ISSUE TITLE
Pulse Audio API not found.

### ISSUE THREAD

**Issue by w4mmp** [illuusio/portaudio#5]
This version of Portaudio does not report Pulse Audio as a host API type.

**To Reproduce**
This is a snippet of the application code that reports the host APIs available:

printf( "PortAudio version: 0x%08X\n", Pa_GetVersion());
 printf( "Version text: '%s'\n", Pa_GetVersionInfo()->versionText );
hostApiCount = Pa_GetHostApiCount();  

    for (j = 0; j < hostApiCount; j++) {
        lpApiInfo = Pa_GetHostApiInfo(j);
        print_time();
        fprintf(G_fp_logfile, "[%d] main -> Host API: %s\n", line_number++, lpApiInfo->name);
        if (!strncmp("ALSA", lpApiInfo->name, 3)) {
            apiTypeId = j;
        }
    }
**Actual behavior**
Application output:
[07:3:24:41][39] main -> PortAudio Version: 0x  130700
[07:3:24:41][40] main -> PortAudio Version text: 'PortAudio V19.7.0-devel, revision unknown'
[07:3:24:41][41] main -> Host API: ALSA
[07:3:24:41][42] main -> Host API: OSS
_**NOTE:  PULSE IS NOT REPORTED AS A VALID HOST API**_

**Desktop (please complete the following information):**
 - OS: Raspberry O.S.  (Debian Buster)
 - OS Linux multus-sdr 5.10.63-v7l+ #1488 SMP Thu Nov 18 16:15:28 GMT 2021 armv7l
 - PortAudio version: This source version
 - If Windows or Linux, which Host API:  PULSE

**Additional context**
I have downloaded, built and installed this version of PortAudio on a Raspberry Pi 4B.  The application was recompiled to pick up the correct portaudio library.  
Also, Pulse Audio is installed correctly.   It is configured to communicate with a Pulse Audio server running on a Windows machine.  It has been verified as working with playing a MP3 audio file via mplayer.  The MP3 audio is sent to the Windows machine and heard on the default speakers.

**Comment by illuusio** [comment]
Thank you for the report and sorry to get late in to ball. I didn't realize that I'm getting upstream as people starting to commit Bugs and PR's to this my little hobby audio project.
Very strange bug indeed. Are you sure that PulseAudio is regonized. I have to test with Raspberry Pi as I need to make some stuff with it.

If you want to test binary package you can fetch Rasperry Pi here:
```
https://download.opensuse.org/repositories/home:/illuusio:/portaudio/Raspbian_11/
```

**Comment by illuusio** [comment]
Please test Pulseaudio on Portaudio master. I'll close this and open new one on Portaudio issues if it's still issue.
