### ISSUE TITLE
Minor copy-paste error and propsed changes to default latency settings.

### ISSUE THREAD

**Issue by kleinerm** [illuusio/portaudio#7]
I've been testing your branch already for a few days, and i have added support to my own audio driver for this new Pulseaudio host api of yours. Cfe. the commits from https://github.com/kleinerm/Psychtoolbox-3/commits/master in the date range 13th - 15th January 2022. Good work, i'm impressed how well it already works! My driver "PsychPortAudio" only uses the callback api for audio recording and playback, i didn't test the blocking api at all.

Anyway, apart from the pull request which fixes audio timestamping, here are a few more suggestions based on my experience with your code so far:

https://github.com/illuusio/portaudio/blob/58c0d338be283d5b63ebd9c1889c8f7efbb351ac/src/hostapi/pulseaudio/pa_linux_pulseaudio.c#L303

Should be ``= defaultHighInputLatency`` not ``defaultHighOutputLatency``.

That said, in all calls to _PaPulseAudio_AddAudioDevice() i would suggest hard-coding some reasonable value for the defaultHigh/LowInput/OutputLatency instead of using ``0`` for the default devices and ``l->latency / (double)PA_USEC_PER_SEC`` or ``l->configured_latency / (double)PA_USEC_PER_SEC`` like e.g., in https://github.com/illuusio/portaudio/blob/58c0d338be283d5b63ebd9c1889c8f7efbb351ac/src/hostapi/pulseaudio/pa_linux_pulseaudio.c#L351

When playing with your branch i realized that the ``l->configured_latency`` and ``l->latency`` values change dynamically all the time, depending on what other audio clients are sharing the pulseaudio source/sink device with the Portaudio client, and how they are changing their settings. If no other clients are using a sink/source then those values are all 0 while the sink is suspended. If the sink is idle, the values are very high - over a second. Otherwise, when the source/sink is active, values change dynamically from second to second. So reporting such variable and dynamic values as defaults doesn't really make sense. Additionally those values are only assigned in Portaudio during host api initialization as far as i understand, ie. Pa_Initialize(), so dynamic values make even less sense.

0 is not a good hard-coded default, because it breaks existing clients which try to calculate something based on those values. When i played with your Pulseaudio branch on a standard AMD Ryzen 5 2400G PC from early 2019 and onboard HDA sound chips and onboard AMD graphics HDMI/Displayport audio, i found these values to work reasonably well:

defaultHighInput/OutputLatency = 0.040
defaultLowInput/OutputLatency = 0.015

At 0.015 = 15 msecs, i still got crackle-free audio. So maybe something along those lines?

Best and thanks for your great work!
-mario

**Comment by illuusio** [comment]
Very reasonable calculations. Much better than mine :smiley:! Please make PR so I can see the results.
