### ISSUE TITLE
More descriptive names for Pulseaudio default source/sink?

### ISSUE THREAD

**Issue by kleinerm** [illuusio/portaudio#8]
https://github.com/illuusio/portaudio/blob/58c0d338be283d5b63ebd9c1889c8f7efbb351ac/src/hostapi/pulseaudio/pa_linux_pulseaudio.c#L597

and

https://github.com/illuusio/portaudio/blob/58c0d338be283d5b63ebd9c1889c8f7efbb351ac/src/hostapi/pulseaudio/pa_linux_pulseaudio.c#L616

name both default sink and source as "Default". ALSA names its default audio device "default". This is a bit confusing when it shows up in UI's.

I'd propose something along the line of "DefaultPulseSink" and "DefaultPulseSource" to reduce the potential for confusion.

Thanks,
-mario

**Comment by illuusio** [comment]
Yes sort of. Be free to make PR about this this. I don't know if some apps get confused if they seek for default.
